version: "1.0"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD : Test@123
      MYSQL_DATABASE : bankappdb
    healthcheck:
      # mysqladmin ping returns 0 if the server is running
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-pTest@123"]
      interval: 10s       # Time between checks
      timeout: 5s        # Time to wait for a response
      retries: 5         # Number of failures before marking "unhealthy"
      start_period: 30s
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks: 
      - bankapp-nw

  bankapp:
    build: .
    container_name: bankapp
    ports:
      - "8090:8090"
    environment:
      MYSQL_HOST : mysql
      MYSQL_PORT : 3306 
      MYSQL_DATABASE : bankappdb
      MYSQL_USER : root
      MYSQL_PASSWORD : Test@123
    depends_on:
      mysql :
        condition : service_healthy
    networks:
      - bankapp-nw
networks:
  bankapp-nw:
    driver : bridge

volumes:
  mysql-data: 
