apiVersion: v1
kind: ConfigMap
metadata:
  name: bankapp-config-map
  namespace: bankapp
data:
    MYSQL_DATABASE: bankappdb
    MYSQL_HOST: mysql-service               # Service name used as hostname inside Docker network
    MYSQL_PORT: "3306"              # MySQL port inside the container network
    MYSQL_USER: root
