name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:
    code_quality:
        uses: ./.github/workflows/code_quality.yml

    security_scan: 
        needs: code_quality
        uses: ./.github/workflows/security_scan.yml

    dependency_check:
        needs: security_scan 
        uses: ./.github/workflows/dependency_check.yml