name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:

    code_quality:
        uses: ./.github/workflows/code_quality.yml

    secrity_scan:
        needs: code_quality
        uses: ./.github/workflows/security_scan.yml

    dependency_check:
        uses: ./.github/workflows/dependency_check.yml