name: DevSecOps Pipeline

on:
    workflow_dispatch:

jobs:
    code_quality:
        uses: ./.github/workflows/code_quality.yml

    secrates_scan: 
        needs: code_quality
        uses: ./.github/workflows/secrates_scan.yml

    dependency_check:
        needs: secrates_scan 
        uses: ./.github/workflows/dependency_check.yml